# Generated by Django 2.2.6 on 2019-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='visible_password',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
