# Generated by Django 2.2.6 on 2019-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191026_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='visible_password',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
