# Generated by Django 2.2.2 on 2019-11-20 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191103_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
