# Generated by Django 2.2.6 on 2019-10-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_family'),
        ('structure', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=6)),
                ('pay_time', models.DateTimeField()),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('NotPaid', 'not paid'), ('Online', 'online'), ('Cash', 'cash')], default='NotPaid', max_length=32)),
                ('add_rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt.Add_Rent')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Family')),
            ],
        ),
    ]
