# Generated by Django 2.2.6 on 2019-10-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_unit'),
        ('account', '0004_auto_20191026_1531'),
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=6)),
                ('pay_time', models.DateTimeField()),
                ('unit_id', models.ManyToManyField(to='structure.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('NotPaid', 'not paid'), ('Online', 'online'), ('Cash', 'cash')], default='NotPaid', max_length=32)),
                ('add_damage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debt.Add_Damage')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Family')),
            ],
        ),
    ]
