# Generated by Django 2.2.2 on 2019-11-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_auto_20191103_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_rent',
            name='subject',
            field=models.CharField(choices=[('Water', 'water'), ('Charge', 'charge')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
