# Generated by Django 2.2.2 on 2019-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_add_rent_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
