# Generated by Django 2.2.2 on 2019-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0005_rent_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
