# Generated by Django 2.2.6 on 2019-10-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_family'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('floor', models.CharField(max_length=32)),
                ('plaque', models.IntegerField()),
                ('rent_status', models.CharField(choices=[('empty', 'Empty'), ('protector', 'Protector'), ('tenant', 'Tenant')], default='empty', max_length=32)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='structure.Apartment')),
                ('family_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Family')),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
