# Generated by Django 2.2.6 on 2019-10-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'permissions': (('can_read', 'can read'),)},
        ),
    ]
