# Generated by Django 2.2.2 on 2019-11-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20191028_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fu', to='account.Family'),
        ),
    ]
